name: e2e-local-cluster

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  kind:
    name: Kubernetes
    strategy:
      fail-fast: false
      matrix:
        k8s: [ {version: 'v1.25.0', port: '7825'}, {version: 'v1.26.0', port: '7826'}, {version: 'v1.27.0', port: '7827'} ]
    runs-on: ubuntu-20.04
    steps:
      - name: Clone host-scanner repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker \
            build . \
            --file build/Dockerfile \
            -t kubescape/host-scanner:test \
            --build-arg BUILD_VERSION=latest
        env: 
          CGO_ENABLED: 0

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Install Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true
          version: v0.18.0

      - name: Setup test clusters
        run: |
          kind create cluster \
            --kubeconfig test-${{ matrix.k8s.version }} \
            --name test-${{ matrix.k8s.version }} \
            --image kindest/node:${{ matrix.k8s.version }}

      - name: Load host-scanner image into Kind
        run: |
          kind load \
            docker-image \
            kubescape/host-scanner:test \
            --nodes test-${{ matrix.k8s.version }}-control-plane \
            --name test-${{ matrix.k8s.version }}

      - name: Install host-scanner
        run: |
          kubectl apply \
            --kubeconfig test-${{ matrix.k8s.version }} \
            -f deployment/host-scanner.yaml

      - name: Wait for host-scanner ready
        run: |
          sleep 15
          kubectl wait \
            --for=condition=ready \
            pod \
            -l name=host-scanner \
            --namespace $(cat deployment/host-scanner.yaml | grep -oP "(?<=namespace: )(.*)") \
            --timeout=300s \
            --kubeconfig test-${{ matrix.k8s.version }}
      
      - name: Setup Kubernetes port-forward daemon
        run: |
          kubectl port-forward \
            'daemonset/host-scanner' \
            ${{ matrix.k8s.port }}:7888 \
            --namespace=$(cat deployment/host-scanner.yaml | grep -oP "(?<=namespace: )(.*)") \
            --kubeconfig=test-${{ matrix.k8s.version }} &

      - name: Run e2e tests
        working-directory: ./e2e
        run: |
          go test -tags kind -v -ginkgo.v -args -port ${{ matrix.k8s.port }}
        env:
          KUBECONFIG: ../test-${{ matrix.k8s.version }}
