name: Test Suite

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-host-scanner-image:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image version
        id: image-version
        run: echo '::set-output name=IMAGE_VERSION::test'

      - name: Set image name
        id: image-name
        run: echo '::set-output name=IMAGE_NAME::quay.io/${{ github.repository_owner }}/host-scanner'

      - name: Login to Quay.io
        env:
          QUAY_PASSWORD: ${{ secrets.QUAYIO_REGISTRY_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAYIO_REGISTRY_USERNAME }}
        run: docker login -u="${QUAY_USERNAME}" -p="${QUAY_PASSWORD}" quay.io

      - name: Build the Docker image
        run: |
          docker buildx \
            build . \
            --file build/Dockerfile \
            --tag ${{ steps.image-name.outputs.IMAGE_NAME }}:${{ steps.image-version.outputs.IMAGE_VERSION }} \
            --tag ${{ steps.image-name.outputs.IMAGE_NAME }}:test \
            --build-arg BUILD_VERSION=${{ steps.image-version.outputs.IMAGE_VERSION }} \
            --push
        env:
          CGO_ENABLED: 0

  integration-test:
    needs: [build-host-scanner-image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout host-scanner repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3

      - name: Checkout systests repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # ratchet:actions/checkout@v3
        with:
          repository: armosec/system-tests
          path: system-tests

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # ratchet:actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: create env
        run: ./create_env.sh
        working-directory: system-tests/

      - name: Create k8s Kind Cluster
        id: kind-cluster-install
        uses: helm/kind-action@d08cf6ff1575077dee99962540d77ce91c62387d # ratchet:helm/kind-action@v1.3.0
        with:
          cluster_name: integration

      - name: run integration test
        env:
          CUSTOMER: ${{ secrets.CUSTOMER }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID_PROD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY_PROD }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          source systests_python_env/bin/activate

          python3 systest-cli.py                \
            -t host_scanner_with_hostsensorrule \
            -b production                       \
            -c CyberArmorTests                  \
            --duration 3                        \
            --logger DEBUG                      \
            --kwargs ks_branch=release          \
            host_scan_yaml=../deployment/host-scanner.yaml

          deactivate
        working-directory: system-tests/

  e2e-test-multi-version-support:
    strategy:
      fail-fast: false
      matrix:
        k8s: [
          {
            name: 'kind',
            version: 'v1.25.0',
            port: '7825'
          },
          {
            name: 'kind',
            version: 'v1.26.0',
            port: '7826'
          },
          {
            name: 'kind',
            version: 'v1.27.0',
            port: '7827'
          }
        ]
    needs: [build-host-scanner-image]
    runs-on: ubuntu-latest
    steps:
      - name: Clone host-scanner repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Install Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true
          version: v0.18.0

      - name: Setup test clusters
        run: |
          kind create cluster \
            --kubeconfig test-${{ matrix.k8s.version }} \
            --name test-${{ matrix.k8s.version }} \
            --image kindest/node:${{ matrix.k8s.version }}

      - name: Install host-scanner
        run: |
          kubectl apply \
            --kubeconfig test-${{ matrix.k8s.version }} \
            -f deployment/host-scanner.yaml

      - name: Get Namespace
        id: namespace
        run: |
          namespace=$(cat deployment/host-scanner.yaml | grep -oP "(?<=namespace: )(.*)")
          echo "NAMESPACE=$namespace" >> $GITHUB_OUTPUT

      - name: Wait for host-scanner ready
        run: |
          sleep 15
          kubectl wait \
            --for=condition=ready \
            pod \
            -l name=host-scanner \
            --namespace ${{ steps.namespace.outputs.NAMESPACE }} \
            --timeout=300s \
            --kubeconfig test-${{ matrix.k8s.version }}

      - name: Setup Kubernetes port-forward daemon
        run: |
          kubectl port-forward \
            'daemonset/host-scanner' \
            ${{ matrix.k8s.port }}:7888 \
            --namespace=${{ steps.namespace.outputs.NAMESPACE }} \
            --kubeconfig=test-${{ matrix.k8s.version }} &

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Run e2e tests
        working-directory: ./e2e
        run: |
          go test \
            -tags ${{ matrix.k8s.name }} \
            -v -ginkgo.v \
            -args -port ${{ matrix.k8s.port }}
        env:
          KUBECONFIG: ../test-${{ matrix.k8s.version }}
